services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: wealth-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

volumes:
  dynamodb-data:
